apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: the-eks-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 40
    volumeType: gp2
    tags:
      nodegroup-type: worker

 
